_prefs: 
  mapid: wienerblut.ed4762b1
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 13.4286
  - 52.4984
  - 16
description: Wiener Blut Map Style
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 19
minzoom: 12
name: Wiener Blut
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
